spring.application.name=usth

server.port=8080

# Cập nhật cổng 3307 và password mới
spring.datasource.url=jdbc:mysql://localhost:3307/usth_aviation?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=HAILONG_DEV

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Upload ảnh
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB